
-- Snowflake Schema for XYZ_Financials_Securities
-- Optimized for Snowflake's cloud data warehouse architecture

CREATE DATABASE IF NOT EXISTS XYZ_FINANCIALS_SECURITIES;
USE DATABASE XYZ_FINANCIALS_SECURITIES;

CREATE SCHEMA IF NOT EXISTS LENDING;
USE SCHEMA LENDING;

-- Customers Table
CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    SSN VARCHAR(11) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    ANNUAL_INCOME NUMBER(15,2),
    EMPLOYMENT_STATUS VARCHAR(50),
    EMPLOYER VARCHAR(100),
    YEARS_EMPLOYED NUMBER(38,0),
    CREDIT_SCORE NUMBER(38,0),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAST_UPDATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT UQ_CUSTOMERS_SSN UNIQUE (SSN)
);

-- Create sequence for Customer ID
CREATE OR REPLACE SEQUENCE SEQ_CUSTOMER_ID START = 1000 INCREMENT = 1;

-- Mortgage Products Table
CREATE OR REPLACE TABLE MORTGAGE_PRODUCTS (
    PRODUCT_ID NUMBER(38,0) NOT NULL,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    PRODUCT_TYPE VARCHAR(50) NOT NULL,
    TERM NUMBER(38,0) NOT NULL,
    BASE_INTEREST_RATE NUMBER(5,3) NOT NULL,
    MIN_CREDIT_SCORE NUMBER(38,0) NOT NULL,
    MAX_LTV NUMBER(5,2) NOT NULL,
    MIN_LOAN_AMOUNT NUMBER(15,2) NOT NULL,
    MAX_LOAN_AMOUNT NUMBER(15,2) NOT NULL,
    ORIGINATION_FEE NUMBER(5,2) DEFAULT 0,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CONSTRAINT PK_MORTGAGE_PRODUCTS PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT UQ_MORTGAGE_PRODUCTS_NAME UNIQUE (PRODUCT_NAME)
);

-- Property Details Table
CREATE OR REPLACE TABLE PROPERTY_DETAILS (
    PROPERTY_ID NUMBER(38,0) NOT NULL,
    ADDRESS_LINE1 VARCHAR(100) NOT NULL,
    ADDRESS_LINE2 VARCHAR(100),
    CITY VARCHAR(50) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    ZIP_CODE VARCHAR(10) NOT NULL,
    COUNTRY VARCHAR(50) DEFAULT 'USA',
    PROPERTY_TYPE VARCHAR(50) NOT NULL,
    YEAR_BUILT NUMBER(38,0),
    SQUARE_FEET NUMBER(38,0),
    BEDROOMS NUMBER(38,0),
    BATHROOMS NUMBER(3,1),
    PURCHASE_PRICE NUMBER(15,2),
    CURRENT_VALUE NUMBER(15,2),
    LAST_APPRAISAL_DATE DATE,
    LAST_APPRAISAL_VALUE NUMBER(15,2),
    TAX_ASSESSMENT_VALUE NUMBER(15,2),
    ANNUAL_TAX_AMOUNT NUMBER(10,2),
    HOA_FEES NUMBER(10,2) DEFAULT 0,
    FLOOD_ZONE VARCHAR(10),
    PROPERTY_TAX_ID VARCHAR(50),
    LATITUDE NUMBER(9,6),
    LONGITUDE NUMBER(9,6),
    CONSTRAINT PK_PROPERTY_DETAILS PRIMARY KEY (PROPERTY_ID)
);

-- Loan Officers Table
CREATE OR REPLACE TABLE LOAN_OFFICERS (
    OFFICER_ID NUMBER(38,0) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    BRANCH_ID NUMBER(38,0),
    HIRE_DATE DATE NOT NULL,
    COMMISSION_RATE NUMBER(5,2) DEFAULT 0,
    STATUS VARCHAR(20) DEFAULT 'Active',
    CONSTRAINT PK_LOAN_OFFICERS PRIMARY KEY (OFFICER_ID),
    CONSTRAINT UQ_LOAN_OFFICERS_EMAIL UNIQUE (EMAIL)
);

-- Applications Table
CREATE OR REPLACE TABLE APPLICATIONS (
    APPLICATION_ID NUMBER(38,0) NOT NULL,
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    PRODUCT_ID NUMBER(38,0) NOT NULL,
    OFFICER_ID NUMBER(38,0) NOT NULL,
    APPLICATION_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LOAN_AMOUNT NUMBER(15,2) NOT NULL,
    LOAN_PURPOSE VARCHAR(50) NOT NULL,
    STATUS VARCHAR(50) DEFAULT 'Submitted',
    CLOSING_DATE DATE,
    APPLICATION_FEE NUMBER(10,2),
    DTI NUMBER(5,2),
    PROPERTY_VALUE NUMBER(15,2),
    LTV NUMBER(5,2),
    RATE_OFFERED NUMBER(5,3),
    TERM_OFFERED NUMBER(38,0),
    DENIAL_REASON VARCHAR(255),
    CONSTRAINT PK_APPLICATIONS PRIMARY KEY (APPLICATION_ID),
    CONSTRAINT FK_APPLICATIONS_CUSTOMERS FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    CONSTRAINT FK_APPLICATIONS_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES MORTGAGE_PRODUCTS(PRODUCT_ID),
    CONSTRAINT FK_APPLICATIONS_OFFICERS FOREIGN KEY (OFFICER_ID) REFERENCES LOAN_OFFICERS(OFFICER_ID)
);

-- Create sequence for Application ID
CREATE OR REPLACE SEQUENCE SEQ_APPLICATION_ID START = 10000 INCREMENT = 1;

-- Securities Table
CREATE OR REPLACE TABLE SECURITIES (
    SECURITY_ID NUMBER(38,0) NOT NULL,
    SECURITY_NAME VARCHAR(100) NOT NULL,
    SECURITY_TYPE VARCHAR(50) NOT NULL,
    CUSIP VARCHAR(9),
    ISSUE_DATE DATE NOT NULL,
    MATURITY_DATE DATE NOT NULL,
    COUPON_RATE NUMBER(5,3) NOT NULL,
    FACE_VALUE NUMBER(15,2) NOT NULL,
    CURRENT_BALANCE NUMBER(15,2) NOT NULL,
    ISSUER VARCHAR(100) NOT NULL,
    RATING VARCHAR(10),
    STATUS VARCHAR(20) DEFAULT 'Active',
    LAST_TRADE_DATE DATE,
    LAST_TRADE_PRICE NUMBER(10,3),
    CONSTRAINT PK_SECURITIES PRIMARY KEY (SECURITY_ID)
);

-- Loans Table
CREATE OR REPLACE TABLE LOANS (
    LOAN_ID NUMBER(38,0) NOT NULL,
    APPLICATION_ID NUMBER(38,0) NOT NULL,
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    PROPERTY_ID NUMBER(38,0) NOT NULL,
    PRODUCT_ID NUMBER(38,0) NOT NULL,
    LOAN_AMOUNT NUMBER(15,2) NOT NULL,
    INTEREST_RATE NUMBER(5,3) NOT NULL,
    TERM NUMBER(38,0) NOT NULL,
    ORIGINATION_DATE DATE NOT NULL,
    MATURITY_DATE DATE NOT NULL,
    MONTHLY_PAYMENT NUMBER(12,2) NOT NULL,
    REMAINING_BALANCE NUMBER(15,2) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'Active',
    ESCROW_REQUIRED BOOLEAN DEFAULT TRUE,
    PMI_REQUIRED BOOLEAN DEFAULT FALSE,
    PMI_AMOUNT NUMBER(10,2) DEFAULT 0,
    FIRST_PAYMENT_DATE DATE NOT NULL,
    NEXT_PAYMENT_DATE DATE,
    PAYMENT_FREQUENCY VARCHAR(20) DEFAULT 'Monthly',
    SECURITY_ID NUMBER(38,0),
    LAST_UPDATED_DATE DATE,
    CONSTRAINT PK_LOANS PRIMARY KEY (LOAN_ID),
    CONSTRAINT FK_LOANS_APPLICATIONS FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATIONS(APPLICATION_ID),
    CONSTRAINT FK_LOANS_CUSTOMERS FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    CONSTRAINT FK_LOANS_PROPERTIES FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY_DETAILS(PROPERTY_ID),
    CONSTRAINT FK_LOANS_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES MORTGAGE_PRODUCTS(PRODUCT_ID),
    CONSTRAINT FK_LOANS_SECURITIES FOREIGN KEY (SECURITY_ID) REFERENCES SECURITIES(SECURITY_ID),
    CONSTRAINT CK_LOANS_LOAN_AMOUNT CHECK (LOAN_AMOUNT > 0),
    CONSTRAINT CK_LOANS_INTEREST_RATE CHECK (INTEREST_RATE >= 0 AND INTEREST_RATE <= 50)
);

-- Create sequence for Loan ID
CREATE OR REPLACE SEQUENCE SEQ_LOAN_ID START = 100000 INCREMENT = 1;

-- Payments Table
CREATE OR REPLACE TABLE PAYMENTS (
    PAYMENT_ID NUMBER(38,0) NOT NULL,
    LOAN_ID NUMBER(38,0) NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    PAYMENT_AMOUNT NUMBER(12,2) NOT NULL,
    PRINCIPAL_AMOUNT NUMBER(12,2) NOT NULL,
    INTEREST_AMOUNT NUMBER(12,2) NOT NULL,
    ESCROW_AMOUNT NUMBER(12,2) DEFAULT 0,
    LATE_FEE_AMOUNT NUMBER(10,2) DEFAULT 0,
    PAYMENT_METHOD VARCHAR(50),
    TRANSACTION_ID VARCHAR(100),
    PAYMENT_STATUS VARCHAR(20) DEFAULT 'Processed',
    PROCESSED_DATE TIMESTAMP_NTZ,
    CONSTRAINT PK_PAYMENTS PRIMARY KEY (PAYMENT_ID),
    CONSTRAINT FK_PAYMENTS_LOANS FOREIGN KEY (LOAN_ID) REFERENCES LOANS(LOAN_ID),
    CONSTRAINT CK_PAYMENTS_AMOUNTS CHECK (PAYMENT_AMOUNT > 0 AND PRINCIPAL_AMOUNT >= 0 AND INTEREST_AMOUNT >= 0)
);

-- Escrow Accounts Table
CREATE OR REPLACE TABLE ESCROW_ACCOUNTS (
    ESCROW_ID NUMBER(38,0) NOT NULL,
    LOAN_ID NUMBER(38,0) NOT NULL,
    CURRENT_BALANCE NUMBER(12,2) DEFAULT 0,
    PROPERTY_TAX_AMOUNT NUMBER(12,2) DEFAULT 0,
    PROPERTY_INSURANCE_AMOUNT NUMBER(12,2) DEFAULT 0,
    PMI_AMOUNT NUMBER(12,2) DEFAULT 0,
    CUSHION_AMOUNT NUMBER(12,2) DEFAULT 0,
    LAST_ANALYSIS_DATE DATE,
    NEXT_ANALYSIS_DATE DATE,
    MONTHLY_CONTRIBUTION NUMBER(12,2) DEFAULT 0,
    SHORTAGE_AMOUNT NUMBER(12,2) DEFAULT 0,
    CONSTRAINT PK_ESCROW_ACCOUNTS PRIMARY KEY (ESCROW_ID),
    CONSTRAINT UQ_ESCROW_ACCOUNTS_LOAN UNIQUE (LOAN_ID),
    CONSTRAINT FK_ESCROW_ACCOUNTS_LOANS FOREIGN KEY (LOAN_ID) REFERENCES LOANS(LOAN_ID)
);

-- Escrow Transactions Table
CREATE OR REPLACE TABLE ESCROW_TRANSACTIONS (
    TRANSACTION_ID NUMBER(38,0) NOT NULL,
    ESCROW_ID NUMBER(38,0) NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    TRANSACTION_TYPE VARCHAR(50) NOT NULL,
    AMOUNT NUMBER(12,2) NOT NULL,
    DESCRIPTION VARCHAR(255),
    REFERENCE VARCHAR(100),
    CONSTRAINT PK_ESCROW_TRANSACTIONS PRIMARY KEY (TRANSACTION_ID),
    CONSTRAINT FK_ESCROW_TRANSACTIONS_ESCROW FOREIGN KEY (ESCROW_ID) REFERENCES ESCROW_ACCOUNTS(ESCROW_ID)
);

-- Defaults and Foreclosures Table
CREATE OR REPLACE TABLE DEFAULTS_FORECLOSURES (
    DEFAULT_ID NUMBER(38,0) NOT NULL,
    LOAN_ID NUMBER(38,0) NOT NULL,
    DEFAULT_DATE DATE NOT NULL,
    STAGE VARCHAR(50) NOT NULL,
    REASON_CODE VARCHAR(50),
    RESOLUTION_TYPE VARCHAR(50),
    RESOLUTION_DATE DATE,
    LOSS_AMOUNT NUMBER(15,2),
    COLLECTION_AGENCY VARCHAR(100),
    LEGAL_FILING_DATE DATE,
    LEGAL_CASE_NUMBER VARCHAR(50),
    NOTES VARCHAR(16777216),
    CONSTRAINT PK_DEFAULTS_FORECLOSURES PRIMARY KEY (DEFAULT_ID),
    CONSTRAINT FK_DEFAULTS_FORECLOSURES_LOANS FOREIGN KEY (LOAN_ID) REFERENCES LOANS(LOAN_ID)
);

-- Servicing Rights Table
CREATE OR REPLACE TABLE SERVICING_RIGHTS (
    SERVICING_ID NUMBER(38,0) NOT NULL,
    LOAN_ID NUMBER(38,0) NOT NULL,
    SERVICER_NAME VARCHAR(100) NOT NULL,
    SERVICER_ID NUMBER(38,0),
    TRANSFER_DATE DATE NOT NULL,
    MSR_VALUE NUMBER(15,2),
    SERVICING_FEE NUMBER(5,3),
    SUBSERVICER_NAME VARCHAR(100),
    TRANSFER_REASON VARCHAR(100),
    CONSTRAINT PK_SERVICING_RIGHTS PRIMARY KEY (SERVICING_ID),
    CONSTRAINT FK_SERVICING_RIGHTS_LOANS FOREIGN KEY (LOAN_ID) REFERENCES LOANS(LOAN_ID)
);

-- Customer Addresses Table
CREATE OR REPLACE TABLE CUSTOMER_ADDRESSES (
    ADDRESS_ID NUMBER(38,0) NOT NULL,
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    ADDRESS_TYPE VARCHAR(20) NOT NULL,
    ADDRESS_LINE1 VARCHAR(100) NOT NULL,
    ADDRESS_LINE2 VARCHAR(100),
    CITY VARCHAR(50) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    ZIP_CODE VARCHAR(10) NOT NULL,
    COUNTRY VARCHAR(50) DEFAULT 'USA',
    START_DATE DATE,
    END_DATE DATE,
    CONSTRAINT PK_CUSTOMER_ADDRESSES PRIMARY KEY (ADDRESS_ID),
    CONSTRAINT FK_CUSTOMER_ADDRESSES_CUSTOMERS FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

-- Documents Registry Table
CREATE OR REPLACE TABLE DOCUMENTS_REGISTRY (
    DOCUMENT_ID NUMBER(38,0) NOT NULL,
    APPLICATION_ID NUMBER(38,0) NOT NULL,
    DOCUMENT_TYPE VARCHAR(100) NOT NULL,
    FILE_NAME VARCHAR(255),
    FILE_LOCATION VARCHAR(255),
    UPLOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    REQUIRED_FLAG BOOLEAN DEFAULT TRUE,
    RECEIVED_FLAG BOOLEAN DEFAULT FALSE,
    APPROVAL_STATUS VARCHAR(20) DEFAULT 'Pending',
    APPROVAL_DATE TIMESTAMP_NTZ,
    APPROVED_BY VARCHAR(100),
    NOTES VARCHAR(16777216),
    CONSTRAINT PK_DOCUMENTS_REGISTRY PRIMARY KEY (DOCUMENT_ID),
    CONSTRAINT FK_DOCUMENTS_REGISTRY_APPLICATIONS FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATIONS(APPLICATION_ID)
);

-- Risk Assessments Table
CREATE OR REPLACE TABLE RISK_ASSESSMENTS (
    ASSESSMENT_ID NUMBER(38,0) NOT NULL,
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    APPLICATION_ID NUMBER(38,0) NOT NULL,
    ASSESSMENT_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREDIT_SCORE NUMBER(38,0) NOT NULL,
    DTI NUMBER(5,2) NOT NULL,
    LTV NUMBER(5,2) NOT NULL,
    FICO_SCORE_SOURCE VARCHAR(50),
    RISK_CLASSIFICATION VARCHAR(20),
    RECOMMENDED_ACTION VARCHAR(50),
    NOTES VARCHAR(16777216),
    CONSTRAINT PK_RISK_ASSESSMENTS PRIMARY KEY (ASSESSMENT_ID),
    CONSTRAINT FK_RISK_ASSESSMENTS_CUSTOMERS FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    CONSTRAINT FK_RISK_ASSESSMENTS_APPLICATIONS FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATIONS(APPLICATION_ID)
);

-- Loan Term Modifications Table
CREATE OR REPLACE TABLE LOAN_TERM_MODIFICATIONS (
    MODIFICATION_ID NUMBER(38,0) NOT NULL,
    LOAN_ID NUMBER(38,0) NOT NULL,
    MODIFICATION_DATE DATE NOT NULL,
    MODIFICATION_TYPE VARCHAR(50) NOT NULL,
    PREVIOUS_INTEREST_RATE NUMBER(5,3),
    NEW_INTEREST_RATE NUMBER(5,3),
    PREVIOUS_TERM NUMBER(38,0),
    NEW_TERM NUMBER(38,0),
    PREVIOUS_PAYMENT NUMBER(12,2),
    NEW_PAYMENT NUMBER(12,2),
    MODIFICATION_FEE NUMBER(10,2),
    REQUIRED_DOCUMENTS VARCHAR(16777216),
    APPROVAL_STATUS VARCHAR(20) DEFAULT 'Pending',
    APPROVED_BY VARCHAR(100),
    NOTES VARCHAR(16777216),
    CONSTRAINT PK_LOAN_TERM_MODIFICATIONS PRIMARY KEY (MODIFICATION_ID),
    CONSTRAINT FK_LOAN_TERM_MODIFICATIONS_LOANS FOREIGN KEY (LOAN_ID) REFERENCES LOANS(LOAN_ID)
);

-- Capital Market Data Table
CREATE OR REPLACE TABLE CAPITAL_MARKET_DATA (
    MARKET_DATA_ID NUMBER(38,0) NOT NULL,
    DATA_DATE DATE NOT NULL,
    DATA_SOURCE VARCHAR(100) NOT NULL,
    TREASURY_10Y NUMBER(5,3),
    FED_FUNDS_RATE NUMBER(5,3),
    LIBOR_3M NUMBER(5,3),
    SOFR NUMBER(5,3),
    MBS_30Y_RATE NUMBER(5,3),
    FANNIE_30Y_RATE NUMBER(5,3),
    FREDDIE_30Y_RATE NUMBER(5,3),
    EFFECTIVE_DATE_START DATE,
    EFFECTIVE_DATE_END DATE,
    CONSTRAINT PK_CAPITAL_MARKET_DATA PRIMARY KEY (MARKET_DATA_ID)
);

-- Audit Log Table
CREATE OR REPLACE TABLE AUDIT_LOG (
    LOG_ID NUMBER(38,0) NOT NULL,
    ENTITY_TYPE VARCHAR(50) NOT NULL,
    ENTITY_ID NUMBER(38,0) NOT NULL,
    ACTION_TYPE VARCHAR(20) NOT NULL,
    ACTION_DATETIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    USER_ID VARCHAR(50) NOT NULL,
    OLD_VALUES VARCHAR(16777216),
    NEW_VALUES VARCHAR(16777216),
    IP_ADDRESS VARCHAR(50),
    APPLICATION_NAME VARCHAR(100),
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (LOG_ID)
);

-- FINRA Fixed Income Table
CREATE OR REPLACE TABLE FINRA_FI (
    SYMBOL VARCHAR(50) NOT NULL,
    ISSUER_NAME VARCHAR(150) NOT NULL,
    COUPON_TYPE VARCHAR(50),
    COUPON_RATE FLOAT,
    MATURITY_DATE DATE NOT NULL,
    DEAL_ID VARCHAR(50),
    TRANCHE_ID VARCHAR(50),
    ISSUE_DESCRIPTION VARCHAR(250) NOT NULL,
    INTEREST_TYPE VARCHAR(50),
    I44A BOOLEAN NOT NULL,
    CUSIP VARCHAR(50) NOT NULL,
    SUB_PROD_TYPE VARCHAR(50),
    PROD_SUBTYPE VARCHAR(50) NOT NULL,
    PROD_TYPE VARCHAR(50),
    ISSUING_AGENCY VARCHAR(100),
    CONVERTIBLE VARCHAR(1),
    CONSTRAINT PK_FINRA_FI PRIMARY KEY (SYMBOL, CUSIP)
);

-- Reference Tables
CREATE OR REPLACE TABLE INTEREST_TYPE (
    ITID NUMBER(38,0) NOT NULL,
    INTEREST_TYPE_ID VARCHAR(10),
    INTEREST_TYPE_DESC VARCHAR(50),
    CONSTRAINT PK_INTEREST_TYPE PRIMARY KEY (ITID)
);

CREATE OR REPLACE TABLE PRODUCT_SUBTYPE (
    PTID NUMBER(38,0) NOT NULL,
    PROD_TYPE VARCHAR(50) NOT NULL,
    PROD_SUBTYPE VARCHAR(50) NOT NULL,
    PST_DESC VARCHAR(100),
    CONSTRAINT PK_PRODUCT_SUBTYPE PRIMARY KEY (PROD_TYPE, PROD_SUBTYPE)
);

-- Create Views
CREATE OR REPLACE VIEW VW_LOAN_PORTFOLIO_OVERVIEW AS
SELECT 
    L.LOAN_ID,
    C.FIRST_NAME || ' ' || C.LAST_NAME AS CUSTOMER_NAME,
    P.ADDRESS_LINE1 || ', ' || P.CITY || ', ' || P.STATE || ' ' || P.ZIP_CODE AS PROPERTY_ADDRESS,
    L.ORIGINATION_DATE,
    L.MATURITY_DATE,
    L.LOAN_AMOUNT,
    L.REMAINING_BALANCE,
    L.INTEREST_RATE,
    L.MONTHLY_PAYMENT,
    L.STATUS,
    MP.PRODUCT_NAME,
    MP.PRODUCT_TYPE,
    S.SECURITY_NAME
FROM LOANS L
JOIN CUSTOMERS C ON L.CUSTOMER_ID = C.CUSTOMER_ID
JOIN PROPERTY_DETAILS P ON L.PROPERTY_ID = P.PROPERTY_ID
JOIN MORTGAGE_PRODUCTS MP ON L.PRODUCT_ID = MP.PRODUCT_ID
LEFT JOIN SECURITIES S ON L.SECURITY_ID = S.SECURITY_ID;

-- Create clustering keys for better query performance
ALTER TABLE LOANS CLUSTER BY (CUSTOMER_ID, ORIGINATION_DATE);
ALTER TABLE PAYMENTS CLUSTER BY (LOAN_ID, PAYMENT_DATE);
ALTER TABLE APPLICATIONS CLUSTER BY (CUSTOMER_ID, APPLICATION_DATE);